import type { StyleProp, ViewStyle } from 'react-native';

export type HoloCardRarity = 'common' | 'rare' | 'legendary';

export type HoloCardLayout = 'single' | 'trio';

export type PoppoHoloCardViewProps = {
  imageUri?: string;
  leftImageUri?: string;
  centerImageUri?: string;
  rightImageUri?: string;
  rarity?: HoloCardRarity;
  leftRarity?: HoloCardRarity;
  centerRarity?: HoloCardRarity;
  rightRarity?: HoloCardRarity;
  layout?: HoloCardLayout;
  cardName?: string;
  typeLong?: string;
  profile?: string;
  rarityLabel?: string;
  serial?: string;
  starCount?: number;
  hp?: string;
  retreatCost?: string;
  hpLabel?: string;
  retreatLabel?: string;
  move1Name?: string;
  move1Damage?: string;
  move1Cost?: string;
  move2Name?: string;
  move2Damage?: string;
  move2Cost?: string;
  moveDescription?: string;
  move2Description?: string;
  moveTraitLabel?: string;
  imageScale?: number;
  imageOffsetX?: number;
  imageOffsetY?: number;
  flavor?: string;
  brandLine?: string;
  showMove2?: boolean;
  showMoveDesc?: boolean;
  showMove2Desc?: boolean;
  showMeta?: boolean;
  showProfile?: boolean;
  showStats?: boolean;
  showCosts?: boolean;
  showBrand?: boolean;
  style?: StyleProp<ViewStyle>;
};
